[package]
name = "scoped_log"
version = "0.1.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "James McGlashan <github@darkfox.id.au>",
]

[dependencies]
log = "*"

[dev-dependencies]
env_logger = "*"
